{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kltn-backend
  labels:
    app: kltn-backend
    app.kubernetes.io/name: backend
spec:
  replicas: {{ .Values.backend.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: kltn-backend
  template:
    metadata:
      labels:
        app: kltn-backend
        app.kubernetes.io/name: backend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort | default .Values.backend.service.port }}
          env:
            {{- range .Values.backend.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          {{- with .Values.backend.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
          {{- with .Values.backend.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
{{- end }}
